### ISSUE TITLE
Not able to upload BMP format

### ISSUE THREAD

**Issue by jeffminsungkim** [ikhsanalatsary/multer-sharp-s3#23]
When I'm trying to upload BMP file to S3, I'm facing the following error below.

`Error: Input buffer contains unsupported image format`

It seems like the `multer` package does not support BMP format. Do you have any ideas?

**Comment by ikhsanalatsary** [comment]
Hi @jeffminsungkim. I think this is same with [this issue](https://github.com/lovell/sharp/issues/543). Because this library is heavy couple with sharp.

**Comment by ikhsanalatsary** [comment]
We can open discussion for this. Maybe, there's any suggestion and workaround from others
