### ISSUE TITLE
multer-sharp-s3 not running with docker node alpine

### ISSUE THREAD

**Issue by almgwary** [ikhsanalatsary/multer-sharp-s3#31]
Docker restart only after node require `multer-sharp-s3
`

Multer Sharp S3 stop nodejs docker without logging any error
 
`Docker Restarting (139) 37 seconds ago`

**Comment by almgwary** [comment]
SOLVED

for Nodejs Docker use

`FROM lambci/lambda:build-nodejs12.x`

it works fine here 

Documentation source https://github.com/lovell/sharp/blob/master/docs/install.md

**Comment by ikhsanalatsary** [comment]
Noted, thanks
