### ISSUE TITLE
{rotate: true} breaks my app

### ISSUE THREAD

**Issue by vladgrecu** [ikhsanalatsary/multer-sharp-s3#32]
![multersharps3](https://user-images.githubusercontent.com/51508637/79644012-d40aed80-81ae-11ea-8ec4-3b8d2ce7beae.png)

Hello, maybe I'm not using the rotate how I should be but in the previous version it worked just fine. Since 0.2.0 whenever I upload an image this happens. I took the liberty of going into the code and as I saw the part that is commented in transformer.js was responsible for things working. Maybe I'm totally off-point but I said to give you my observations since they may be of use to you.

Cheers

**Comment by ikhsanalatsary** [comment]
Hi @vladgrecu, thanks for reporting this. I will check that. But Currently, I am not able to do this in more couple of weeks due to my laptop in the other city. Also, I hope you always safe from covid19 :)

**Comment by vladgrecu** [comment]
Thank you for the fast reply! First of all congratulations for all the work you did here. Awesome job!
I'm safe, things in my country are not that bad and people tend to follow the rules! Hope you are ok to and I'm really curious if me pointing this will help the product out.

I wish you an awesome day!
