### ISSUE TITLE
When I Pass directory Attribute it will not upload in that directory

### ISSUE THREAD

**Issue by shivank44** [ikhsanalatsary/multer-sharp-s3#51]
**My Code:**
const storage = s3Storage({
    // Key: (req, file, cb) => {
    //   crypto.pseudoRandomBytes(16, (err, raw) => {
    //     cb(err, err ? undefined : raw.toString('hex'))
    //   })
    // },
    s3,
    Bucket: bucketName,
    acl: acl,
    metadata: metaData,
    multiple: true,
    resize: [
      { suffix: 'xlg', directory: 'product/extralarge', width: 1200, height: 1200 },
      { suffix: 'lg', directory: 'product/large', width: 800, height: 800 },
      { suffix: 'md', directory: 'product/medium', width: 500, height: 500 },
      { suffix: 'sm', directory: 'product/small', width: 300, height: 300 },
      { suffix: 'xs', directory: 'product/xtrasmall', width: 100 },
      { suffix: 'original', directory: 'product/original' }
    ],
  });

**It just stores as 
bucket/filename-xs.jpg
not as bucket/product/xs/filename.jpg**

My response:
{
    "images": {
        "fieldname": "file",
        "originalname": "1(1).jpg",
        "encoding": "7bit",
        "mimetype": "image/jpeg",
        "xs": {
            "ACL": "public-read",
            "ETag": "\"2f8701ed2c65e6ae4ec68705c3bbbba2\"",
            "Location": "Bucket/6d90e0c93ccd5a31234f25c58dba4915-xs",
            "key": "6d90e0c93ccd5a31234f25c58dba4915-xs",
            "Key": "6d90e0c93ccd5a31234f25c58dba4915-xs",
            "Bucket": "lumier32",
            "directory": "xtrasmall",
            "width": 100,
            "height": 100,
            "premultiplied": false,
            "size": 3375,
            "ContentType": "jpeg"
        },
        "sm": {
            "ACL": "public-read",
            "ETag": "\"003a633ae136ad767df1b661431418c2\"",
            "Location": "Bucket/6d90e0c93ccd5a31234f25c58dba4915-sm",
            "key": "6d90e0c93ccd5a31234f25c58dba4915-sm",
            "Key": "6d90e0c93ccd5a31234f25c58dba4915-sm",
            "Bucket": "lumier32",
            "directory": "small",
            "width": 300,
            "height": 300,
            "premultiplied": false,
            "size": 17346,
            "ContentType": "jpeg"
        },
        "md": {
            "ACL": "public-read",
            "ETag": "\"2e8103cf1bec4e46012c30332138636e\"",
            "Location": "Bucket/6d90e0c93ccd5a31234f25c58dba4915-md",
            "key": "6d90e0c93ccd5a31234f25c58dba4915-md",
            "Key": "6d90e0c93ccd5a31234f25c58dba4915-md",
            "Bucket": "lumier32",
            "directory": "medium",
            "width": 500,
            "height": 500,
            "premultiplied": false,
            "size": 35310,
            "ContentType": "jpeg"
        },
        "original": {
            "ACL": "public-read",
            "ETag": "\"5055954117ccfe24edcea2ddb1ceef48\"",
            "Location": "Bucket/6d90e0c93ccd5a31234f25c58dba4915-original",
            "key": "6d90e0c93ccd5a31234f25c58dba4915-original",
            "Key": "6d90e0c93ccd5a31234f25c58dba4915-original",
            "Bucket": "lumier32",
            "directory": "original",
            "width": 384,
            "height": 384,
            "premultiplied": false,
            "size": 26063,
            "ContentType": "jpeg"
        },
        "lg": {
            "ACL": "public-read",
            "ETag": "\"30a0a0a80c7f6a76ace203bde3d337cd\"",
            "Location": "Bucket/6d90e0c93ccd5a31234f25c58dba4915-lg",
            "key": "6d90e0c93ccd5a31234f25c58dba4915-lg",
            "Key": "6d90e0c93ccd5a31234f25c58dba4915-lg",
            "Bucket": "lumier32",
            "directory": "large",
            "width": 800,
            "height": 800,
            "premultiplied": false,
            "size": 66100,
            "ContentType": "jpeg"
        },
        "xlg": {
            "ACL": "public-read",
            "ETag": "\"dd67b9a9d2c503772b6b84ba78789e25\"",
            "Location": "Bucket/6d90e0c93ccd5a31234f25c58dba4915-xlg",
            "key": "6d90e0c93ccd5a31234f25c58dba4915-xlg",
            "Key": "6d90e0c93ccd5a31234f25c58dba4915-xlg",
            "Bucket": "lumier32",
            "directory": "extralarge",
            "width": 1200,
            "height": 1200,
            "premultiplied": false,
            "size": 113850,
            "ContentType": "jpeg"
        }
    },
    "imageUrl": "Bucket/6d90e0c93ccd5a31234f25c58dba4915-xs",
    "message": "Successfully uploaded!"
}

**Comment by ikhsanalatsary** [comment]
Thank you for addressing this issue. I think there's a missing in this lib 😃 . If you don't mind and can fix this. PR always welcome

**Comment by ikhsanalatsary** [comment]
@shivank44 ah sorry, when you tried earlier the changes have not been published yet to the npm registry 😆. and for version 0.2.2, the changes got replaced with other features due to some conflict 🦆. I will push the fixes asap. Thank you
