### ISSUE TITLE
Upload from URL to S3

### ISSUE THREAD

**Issue by thousandsofraccoons** [ikhsanalatsary/multer-sharp-s3#58]
Thank you for an amazing library. It helps to update user profile pictures very easily. Is there any way to make it work with google auth for new users? 

Google sends profile picture URL like this "https://lh3.googleusercontent.com/a/AATXAJxSeXuBKi9jM9hYezWjz0ePryguXRuGYgRV_OC5=s96-c"

Problem is that sometimes this URL gets expired, so probably better to upload a profile picture to AWS. Is there any way to make it?

**Comment by ikhsanalatsary** [comment]
I think. you can create a stream to download the source and then upload via this library or combine with other library with that functionality. I don't know the specific library.
