### ISSUE TITLE
Enable Sharp ARM 64 support

### ISSUE THREAD

**Issue by abforman** [ikhsanalatsary/multer-sharp-s3#76]
Need to update the version of Sharp, as it doesn't include prebuilt libraries for ARM 64 until version 0.30.0.
Sharp v0.30.1 is the latest as of today.

Reference: https://github.com/lovell/sharp/issues/2938

I could submit a PR if you'd like; should just be a package.json update for sharp to 0.30.1.

Thanks!

**Comment by ikhsanalatsary** [comment]
@abforman I just commented on your PR. Thanks for addressing this.

**Comment by abforman** [comment]
Thank you @ikhsanalatsary and thank you @audaxion!

**Comment by ikhsanalatsary** [comment]
@audaxion Thank you

**Comment by ikhsanalatsary** [comment]
published v0.2.5
