### ISSUE TITLE
Unable to add metadata

### ISSUE THREAD

**Issue by sunnysid3up** [ikhsanalatsary/multer-sharp-s3#9]
Hi, 

Thank you for making this library. It is super useful and I would like to use it for my app in production. I was wondering if it is possible to add metadata and content type to an image when uploading. As of now, I don't see them as options in your README.

I was able to set contentType by using multer-s3 library, but it would be nice if multer-sharp-s3 could have this feature too to avoid having to install both libs :) 

Additionally, I tried adding metadata to an image but it doesn't seem to work. Here's the code I tried.

```javascript
const express = require("express");
const aws = require("aws-sdk");
const multer = require("multer");
const multerS3 = require("multer-s3");
const s3Storage = require("multer-sharp-s3");

...

const storage = s3Storage({
  s3,
  Bucket: "bucket-name",
  contentType: multerS3.AUTO_CONTENT_TYPE,
  metadata: (req, file, cb) => {
    cb(null, { ...req.body });
  },
  Key: (req, file, cb) => {
    const currentTime = getCurrentTime();
    fileName = `${req.body.category}-${currentTime}-${file.originalname}`;
    cb(null, fileName);
  },
  resize: {
    width: 400,
    height: 400
  },
  max: true
});
const upload = multer({ storage });

...
```

Image is uploaded to S3 without added metadata. I tried capitalizing the metadata key to match your other keys' convention, but it gave me this error: `InvalidParameterType: Expected params.Metadata to be a map`.

**Comment by ikhsanalatsary** [comment]
Thanks for creating this ticket. I'm glad this library is useful for you. So, for your problem I think your setup is wrong. Metadata is an options from [putObjectRequest](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) that mapped object string and this lib does not change that. 
```
Metadata : {...yourMeta} 
```
 Instead of `function`

**Comment by sunnysid3up** [comment]
Hi, thank you for your reply! `Metadata : {...yourMeta}` does work well :) However, I was wondering if a function could work as well. It would be quite useful if we could save the request's query param value or body value as metadata. Sorry I wasn't clear before. I was looking at multer-s3 library earlier and it takes a function for metadata, so I thought it was the original multer's library. Thanks again.

**Comment by ikhsanalatsary** [comment]
Oh, great. I will keep in view your suggestion. For now I will close this issue.
